language: generic 

services:
  - docker

jobs:
  include:
    - stage: compile
      name: 'ROS Dashing'
      script:
        - exec docker run -a STDOUT -a STDERR --rm -v $(pwd):/ws/src/mapviz ros:dashing /ws/src/mapviz/.ros2_build.sh
    - stage: compile
      name: 'ROS Eloquent'
      script:
        - exec docker run -a STDOUT -a STDERR --rm -v $(pwd):/ws/src/mapviz ros:eloquent /ws/src/mapviz/.ros2_build.sh
