Name:           ros-indigo-multires-image
Version:        1.1.0
Release:        0%{?dist}
Summary:        ROS multires_image package

Group:          Development/Libraries
License:        BSD
URL:            https://github.com/swri-robotics/mapviz
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-cv-bridge
Requires:       ros-indigo-gps-common
Requires:       ros-indigo-libqt-core
Requires:       ros-indigo-libqt-opengl
Requires:       ros-indigo-mapviz
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rospy
Requires:       ros-indigo-swri-math-util
Requires:       ros-indigo-swri-transform-util
Requires:       ros-indigo-swri-yaml-util
Requires:       ros-indigo-tf
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cv-bridge
BuildRequires:  ros-indigo-gps-common
BuildRequires:  ros-indigo-libqt-dev
BuildRequires:  ros-indigo-libqt-opengl-dev
BuildRequires:  ros-indigo-mapviz
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-qt-qmake
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-swri-math-util
BuildRequires:  ros-indigo-swri-transform-util
BuildRequires:  ros-indigo-swri-yaml-util
BuildRequires:  ros-indigo-tf

%description
multires_image

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Feb 20 2019 Marc Alban <malban@swri.org> - 1.1.0-0
- Autogenerated by Bloom

* Fri Jan 25 2019 Marc Alban <malban@swri.org> - 1.0.1-0
- Autogenerated by Bloom

* Wed Jan 23 2019 Marc Alban <malban@swri.org> - 1.0.0-0
- Autogenerated by Bloom

* Fri Nov 16 2018 Marc Alban <malban@swri.org> - 0.3.0-0
- Autogenerated by Bloom

* Tue Jul 31 2018 Marc Alban <malban@swri.org> - 0.0.10-0
- Autogenerated by Bloom

* Thu Apr 12 2018 Marc Alban <malban@swri.org> - 0.0.9-0
- Autogenerated by Bloom

* Fri Aug 11 2017 Marc Alban <malban@swri.org> - 0.0.8-0
- Autogenerated by Bloom

* Sun Oct 23 2016 Marc Alban <malban@swri.org> - 0.0.7-0
- Autogenerated by Bloom

* Sun Aug 14 2016 Marc Alban <malban@swri.org> - 0.0.6-0
- Autogenerated by Bloom

* Fri May 20 2016 Marc Alban <malban@swri.org> - 0.0.5-0
- Autogenerated by Bloom

* Wed Jan 06 2016 Marc Alban <malban@swri.org> - 0.0.4-0
- Autogenerated by Bloom

* Mon Sep 28 2015 Marc Alban <malban@swri.org> - 0.0.3-0
- Autogenerated by Bloom

* Sun Sep 27 2015 Marc Alban <malban@swri.org> - 0.0.2-0
- Autogenerated by Bloom

* Sat Sep 26 2015 Marc Alban <malban@swri.org> - 0.0.1-0
- Autogenerated by Bloom

