%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-mapviz
Version:        1.4.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mapviz package

License:        BSD
URL:            https://github.com/swri-robotics/mapviz
Source0:        %{name}-%{version}.tar.gz

Requires:       freeglut-devel
Requires:       glew-devel
Requires:       libXi-devel
Requires:       libXmu-devel
Requires:       qt5-qtbase
Requires:       ros-noetic-cv-bridge
Requires:       ros-noetic-image-transport
Requires:       ros-noetic-marti-common-msgs
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-rosapi
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-rqt-gui
Requires:       ros-noetic-rqt-gui-cpp
Requires:       ros-noetic-std-srvs
Requires:       ros-noetic-swri-transform-util
Requires:       ros-noetic-swri-yaml-util
Requires:       ros-noetic-tf
BuildRequires:  freeglut-devel
BuildRequires:  glew-devel
BuildRequires:  libXi-devel
BuildRequires:  libXmu-devel
BuildRequires:  pkgconfig
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cv-bridge
BuildRequires:  ros-noetic-image-transport
BuildRequires:  ros-noetic-marti-common-msgs
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-pluginlib
BuildRequires:  ros-noetic-rosapi
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-rqt-gui
BuildRequires:  ros-noetic-rqt-gui-cpp
BuildRequires:  ros-noetic-std-srvs
BuildRequires:  ros-noetic-swri-transform-util
BuildRequires:  ros-noetic-swri-yaml-util
BuildRequires:  ros-noetic-tf
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
mapviz

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Thu Oct 22 2020 Marc Alban <malban@swri.org> - 1.4.1-1
- Autogenerated by Bloom

* Tue Jul 28 2020 Marc Alban <malban@swri.org> - 1.4.0-1
- Autogenerated by Bloom

